[build]
    command = "npm i && rollup -c"
    publish = "dist"

[[headers]]
    for = "/*"
    [headers.values]
      	cache-control = '''
    	max-age=604800,
    	s-max-age=604800'''
      	cdn-cache-control = '''
    	max-age=604800,
    	s-max-age=604800'''
        netlify-cdn-cache-control = '''
    	max-age=604800,
    	s-max-age=604800'''